# Generated by Django 5.0.7 on 2024-08-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_remove_group_post_groupposts_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupposts',
            name='image',
            field=models.FileField(upload_to='uploads_model'),
        ),
    ]
