# Generated by Django 5.0.7 on 2024-08-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_groupposts_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupposts',
            old_name='image',
            new_name='file',
        ),
    ]
